// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_2tXr8Gj_-Sc_9NJXrjd5TarXdzHT7R4',
    appId: '1:36695493023:web:40d9446ebccf62804b55aa',
    messagingSenderId: '36695493023',
    projectId: 'app-moviles-chinchay',
    authDomain: 'app-moviles-chinchay.firebaseapp.com',
    storageBucket: 'app-moviles-chinchay.firebasestorage.app',
    measurementId: 'G-4QD7VGEEBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2OxFjHm-WwnxZ8h19oyO86aQq7G7TgOA',
    appId: '1:36695493023:android:45b6db4bfb0813004b55aa',
    messagingSenderId: '36695493023',
    projectId: 'app-moviles-chinchay',
    storageBucket: 'app-moviles-chinchay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwho5t-IJbqiRbUMyzZyuzgz7xXnrbK6s',
    appId: '1:36695493023:ios:18c2a06b7f37ec3c4b55aa',
    messagingSenderId: '36695493023',
    projectId: 'app-moviles-chinchay',
    storageBucket: 'app-moviles-chinchay.firebasestorage.app',
    iosBundleId: 'com.example.prototipe1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwho5t-IJbqiRbUMyzZyuzgz7xXnrbK6s',
    appId: '1:36695493023:ios:18c2a06b7f37ec3c4b55aa',
    messagingSenderId: '36695493023',
    projectId: 'app-moviles-chinchay',
    storageBucket: 'app-moviles-chinchay.firebasestorage.app',
    iosBundleId: 'com.example.prototipe1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_2tXr8Gj_-Sc_9NJXrjd5TarXdzHT7R4',
    appId: '1:36695493023:web:05852b3f92415d8e4b55aa',
    messagingSenderId: '36695493023',
    projectId: 'app-moviles-chinchay',
    authDomain: 'app-moviles-chinchay.firebaseapp.com',
    storageBucket: 'app-moviles-chinchay.firebasestorage.app',
    measurementId: 'G-7CQZ9YEXWM',
  );
}
